### ISSUE TITLE
Issue minimizing to tray (Ubuntu)

### ISSUE THREAD

**Issue by DeflateAwning** [siacentral/host-manager#35] opened 2020-09-28 05:49 UTC
I'm running this on the default Ubuntu 20.04.1 installation, and no tray icon appears when I close out. However, htop confirms that it is running in the background still. I'm wondering if we can **add a configuration option to disable Minimize to Tray**, and also potentially investigate why it is not minimizing. Thanks!

**Comment by n8maninger** [comment] 2020-09-28 23:17
I will definitely investigate why it is not minimizing. In the mean time you should just be able to start it again and it will reopen the existing UI.

What would be the alternative to minimizing to tray? Just shutting down? For most users if you close Host Manager you shutdown your Sia Host, to prevent that I think minimize to tray is pretty important.

**Comment by ThePiGuy** [comment] 2020-09-28 23:42
I'm using the default install (Gnome).

I figured shutting down the Host Manager would be reasonable, but that makes sense that it wouldn't work for most people.

I thought that every time I opened a new Host Manager window, it was creating a new process while old ones continued to run. I just confirmed that this is likely not the case, as `ps aux | grep -i "host manager" | wc -l` counts 9 processes every time, even after closing (while it's closed), and after reopening. 

I suppose this issue is pretty low priority. You can ignore the request to disable "Minimize to Tray" functionality.

**Comment by n8maninger** [comment] 2020-09-28 23:46
Thanks for confirming that it is not starting up a new service every time, but showing the old one.

The platform Host Manager is built-on (Electron) starts a lot of child processes and is not very efficient in general.. It's probably one of my biggest annoyances and something I look forward to dropping entirely..

**Comment by n8maninger** [comment] 2020-10-06 22:38
Looks like this is a known Electron issue, I will keep tabs on the solutions

https://github.com/electron/electron/issues/21445

**Comment by n8maninger** [comment] 2022-08-23 15:06
Updated to electron 20, appears to be fixed

**Closed by n8maninger** 2022-08-23 15:06 UTC
Labels: bug, electron
