### ISSUE TITLE
Update Bundled Sia Daemon to 1.4.7

### ISSUE THREAD

**Issue by Jrjy3** [siacentral/host-manager#22] opened 2020-04-09 22:00 UTC
The newest Sia daemon (1.4.7) is now the lowest version that will communicate with renters. I'm not sure about the details of why, but 1.4.7 needs to be used to continue hosting.

A workaround is to launch the updated SiaUI to start the daemon with the correct version and then launching Host Manager, but this requires manual unlocking of the wallet, so this is not ideal for situations like mine where I have Host Manager running in a VM on my NAS. Any time I restart my NAS, I have to VNC into the VM and manually unlock my wallet.

**Comment by n8maninger** [comment] 2020-04-11 01:56
What version of Host Manager are you on? Host Manager v1.0.13 should come bundled with v1.4.7. Please make sure you're on the latest version.

**Comment by n8maninger** [comment] 2020-04-11 21:10
Closing since I have confirmed that Host Manager v1.0.13 is bundled with v1.4.7 on all platforms

**Closed by n8maninger** 2020-04-11 21:10 UTC

**Comment by Jrjy3** [comment] 2020-04-11 22:14
Got it, the latest version does work. I'm not sure why but the releases page didn't show anything past v1.0.9 until I cleared my cache. Sorry for the false alarm!
